### ISSUE TITLE
def-specs triggers "Method code too large!" compiler error on very large schemas

### ISSUE THREAD

**Issue by solussd** [paren-com/serene#4]

**Comment by domkm** [comment]
Thanks for the report. Fixed in [0.0.2](https://github.com/paren-com/serene/releases/tag/v0.0.2).

**Comment by solussd** [comment]
I'm still experiencing this error in 0.0.2. If I had to guess, I'd say it's being caused by some large enums.

**Comment by domkm** [comment]
This works on GitHub's API, which is huge, so if it fails on your API then I'll need input with which to test a fix. Could you provide me with the results of running Serene's [introspection query](https://github.com/paren-com/serene/blob/master/resources/main/paren/serene/IntrospectionQuery.graphql) against your API?
